//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIClima.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forecasts
    {
        public int Id { get; set; }
        public int dia { get; set; }
        public string clima { get; set; }
        public double coordenada1_X { get; set; }
        public double coordenada1_Y { get; set; }
        public double coordenada2_X { get; set; }
        public double coordenada2_Y { get; set; }
        public double coordenada3_X { get; set; }
        public double coordenada3_Y { get; set; }
        public double perimetro { get; set; }
    }
}
